// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class HttpsCallableRequest {
  HttpsCallableRequest({
    this.appName,
    required this.region,
    this.origin,
    required this.functionName,
    this.parameters,
    required this.timeoutMs,
  });

  String? appName;

  String region;

  String? origin;

  String functionName;

  Object? parameters;

  int timeoutMs;

  Object encode() {
    return <Object?>[
      appName,
      region,
      origin,
      functionName,
      parameters,
      timeoutMs,
    ];
  }

  static HttpsCallableRequest decode(Object result) {
    result as List<Object?>;
    return HttpsCallableRequest(
      appName: result[0] as String?,
      region: result[1]! as String,
      origin: result[2] as String?,
      functionName: result[3]! as String,
      parameters: result[4],
      timeoutMs: result[5]! as int,
    );
  }
}

class HttpsCallableResponse {
  HttpsCallableResponse({
    this.data,
  });

  Object? data;

  Object encode() {
    return <Object?>[
      data,
    ];
  }

  static HttpsCallableResponse decode(Object result) {
    result as List<Object?>;
    return HttpsCallableResponse(
      data: result[0],
    );
  }
}

class _FirebaseFunctionsHostApiCodec extends StandardMessageCodec {
  const _FirebaseFunctionsHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is HttpsCallableRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is HttpsCallableResponse) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return HttpsCallableRequest.decode(readValue(buffer)!);
      case 129: 
        return HttpsCallableResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FirebaseFunctionsHostApi {
  /// Constructor for [FirebaseFunctionsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FirebaseFunctionsHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _FirebaseFunctionsHostApiCodec();

  Future<HttpsCallableResponse> callFunction(HttpsCallableRequest request) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_functions_webos.FirebaseFunctionsHostApi.callFunction';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[request]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as HttpsCallableResponse?)!;
    }
  }

  Future<void> useFunctionsEmulator(String appName, String region, String host, int port) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_functions_webos.FirebaseFunctionsHostApi.useFunctionsEmulator';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, region, host, port]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}
