#pragma once

#include <flutter/plugin_registrar.h>
#include <flutter/encodable_value.h>
#include <map>
#include <memory>
#include <string>

#include "messages.g.h"   // generated by: dart run pigeon --input pigeon/messages.dart
#include <firebase/app.h>
#include <firebase/functions.h>

namespace firebase_functions_webos {

class FirebaseFunctionsWebosPlugin : public flutter::Plugin,
                                     public FirebaseFunctionsHostApi {
 public:
  static void RegisterWithRegistrar(flutter::PluginRegistrar* registrar);

  FirebaseFunctionsWebosPlugin();
  virtual ~FirebaseFunctionsWebosPlugin();

  FirebaseFunctionsWebosPlugin(const FirebaseFunctionsWebosPlugin&) = delete;
  FirebaseFunctionsWebosPlugin& operator=(const FirebaseFunctionsWebosPlugin&) = delete;

  // ---------------------------------------------------------------------------
  // FirebaseFunctionsHostApi overrides (generated by Pigeon from messages.dart)
  // ---------------------------------------------------------------------------

  void CallFunction(const HttpsCallableRequest& request,
    std::function<void(ErrorOr<HttpsCallableResponse>)> result) override;

  void UseFunctionsEmulator(const std::string& app_name,
                             const std::string& region,
                             const std::string& host,
                             int64_t port,
                             std::function<void(std::optional<FlutterError>)> result) override;

 private:
  // Get (or create) a Functions instance for the given app + region.
  firebase::functions::Functions* GetFunctions(const std::string& app_name,
                                                const std::string& region);

  // Convert between flutter::EncodableValue and firebase::Variant.
  static firebase::Variant EncodableToVariant(const flutter::EncodableValue& v);
  static flutter::EncodableValue VariantToEncodable(const firebase::Variant& v);
};

}  // namespace firebase_functions_webos
