// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_functions_webos {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// HttpsCallableRequest

HttpsCallableRequest::HttpsCallableRequest(
  const std::string& region,
  const std::string& function_name,
  int64_t timeout_ms)
 : region_(region),
    function_name_(function_name),
    timeout_ms_(timeout_ms) {}

HttpsCallableRequest::HttpsCallableRequest(
  const std::string* app_name,
  const std::string& region,
  const std::string* origin,
  const std::string& function_name,
  const EncodableValue* parameters,
  int64_t timeout_ms)
 : app_name_(app_name ? std::optional<std::string>(*app_name) : std::nullopt),
    region_(region),
    origin_(origin ? std::optional<std::string>(*origin) : std::nullopt),
    function_name_(function_name),
    parameters_(parameters ? std::optional<EncodableValue>(*parameters) : std::nullopt),
    timeout_ms_(timeout_ms) {}

const std::string* HttpsCallableRequest::app_name() const {
  return app_name_ ? &(*app_name_) : nullptr;
}

void HttpsCallableRequest::set_app_name(const std::string_view* value_arg) {
  app_name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void HttpsCallableRequest::set_app_name(std::string_view value_arg) {
  app_name_ = value_arg;
}


const std::string& HttpsCallableRequest::region() const {
  return region_;
}

void HttpsCallableRequest::set_region(std::string_view value_arg) {
  region_ = value_arg;
}


const std::string* HttpsCallableRequest::origin() const {
  return origin_ ? &(*origin_) : nullptr;
}

void HttpsCallableRequest::set_origin(const std::string_view* value_arg) {
  origin_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void HttpsCallableRequest::set_origin(std::string_view value_arg) {
  origin_ = value_arg;
}


const std::string& HttpsCallableRequest::function_name() const {
  return function_name_;
}

void HttpsCallableRequest::set_function_name(std::string_view value_arg) {
  function_name_ = value_arg;
}


const EncodableValue* HttpsCallableRequest::parameters() const {
  return parameters_ ? &(*parameters_) : nullptr;
}

void HttpsCallableRequest::set_parameters(const EncodableValue* value_arg) {
  parameters_ = value_arg ? std::optional<EncodableValue>(*value_arg) : std::nullopt;
}

void HttpsCallableRequest::set_parameters(const EncodableValue& value_arg) {
  parameters_ = value_arg;
}


int64_t HttpsCallableRequest::timeout_ms() const {
  return timeout_ms_;
}

void HttpsCallableRequest::set_timeout_ms(int64_t value_arg) {
  timeout_ms_ = value_arg;
}


EncodableList HttpsCallableRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(app_name_ ? EncodableValue(*app_name_) : EncodableValue());
  list.push_back(EncodableValue(region_));
  list.push_back(origin_ ? EncodableValue(*origin_) : EncodableValue());
  list.push_back(EncodableValue(function_name_));
  list.push_back(parameters_ ? *parameters_ : EncodableValue());
  list.push_back(EncodableValue(timeout_ms_));
  return list;
}

HttpsCallableRequest HttpsCallableRequest::FromEncodableList(const EncodableList& list) {
  HttpsCallableRequest decoded(
    std::get<std::string>(list[1]),
    std::get<std::string>(list[3]),
    list[5].LongValue());
  auto& encodable_app_name = list[0];
  if (!encodable_app_name.IsNull()) {
    decoded.set_app_name(std::get<std::string>(encodable_app_name));
  }
  auto& encodable_origin = list[2];
  if (!encodable_origin.IsNull()) {
    decoded.set_origin(std::get<std::string>(encodable_origin));
  }
  auto& encodable_parameters = list[4];
  if (!encodable_parameters.IsNull()) {
    decoded.set_parameters(encodable_parameters);
  }
  return decoded;
}

// HttpsCallableResponse

HttpsCallableResponse::HttpsCallableResponse() {}

HttpsCallableResponse::HttpsCallableResponse(const EncodableValue* data)
 : data_(data ? std::optional<EncodableValue>(*data) : std::nullopt) {}

const EncodableValue* HttpsCallableResponse::data() const {
  return data_ ? &(*data_) : nullptr;
}

void HttpsCallableResponse::set_data(const EncodableValue* value_arg) {
  data_ = value_arg ? std::optional<EncodableValue>(*value_arg) : std::nullopt;
}

void HttpsCallableResponse::set_data(const EncodableValue& value_arg) {
  data_ = value_arg;
}


EncodableList HttpsCallableResponse::ToEncodableList() const {
  EncodableList list;
  list.reserve(1);
  list.push_back(data_ ? *data_ : EncodableValue());
  return list;
}

HttpsCallableResponse HttpsCallableResponse::FromEncodableList(const EncodableList& list) {
  HttpsCallableResponse decoded;
  auto& encodable_data = list[0];
  if (!encodable_data.IsNull()) {
    decoded.set_data(encodable_data);
  }
  return decoded;
}


FirebaseFunctionsHostApiCodecSerializer::FirebaseFunctionsHostApiCodecSerializer() {}

EncodableValue FirebaseFunctionsHostApiCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 128:
      return CustomEncodableValue(HttpsCallableRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 129:
      return CustomEncodableValue(HttpsCallableResponse::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
  }
}

void FirebaseFunctionsHostApiCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(HttpsCallableRequest)) {
      stream->WriteByte(128);
      WriteValue(EncodableValue(std::any_cast<HttpsCallableRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(HttpsCallableResponse)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<HttpsCallableResponse>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FirebaseFunctionsHostApi.
const flutter::StandardMessageCodec& FirebaseFunctionsHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&FirebaseFunctionsHostApiCodecSerializer::GetInstance());
}

// Sets up an instance of `FirebaseFunctionsHostApi` to handle messages through the `binary_messenger`.
void FirebaseFunctionsHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FirebaseFunctionsHostApi* api) {
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_functions_webos.FirebaseFunctionsHostApi.callFunction", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const HttpsCallableRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->CallFunction(request_arg, [reply](ErrorOr<HttpsCallableResponse>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_functions_webos.FirebaseFunctionsHostApi.useFunctionsEmulator", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_region_arg = args.at(1);
          if (encodable_region_arg.IsNull()) {
            reply(WrapError("region_arg unexpectedly null."));
            return;
          }
          const auto& region_arg = std::get<std::string>(encodable_region_arg);
          const auto& encodable_host_arg = args.at(2);
          if (encodable_host_arg.IsNull()) {
            reply(WrapError("host_arg unexpectedly null."));
            return;
          }
          const auto& host_arg = std::get<std::string>(encodable_host_arg);
          const auto& encodable_port_arg = args.at(3);
          if (encodable_port_arg.IsNull()) {
            reply(WrapError("port_arg unexpectedly null."));
            return;
          }
          const int64_t port_arg = encodable_port_arg.LongValue();
          api->UseFunctionsEmulator(app_name_arg, region_arg, host_arg, port_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FirebaseFunctionsHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FirebaseFunctionsHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace firebase_functions_webos
