// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_functions_webos {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class FirebaseFunctionsHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Generated class from Pigeon that represents data sent in messages.
class HttpsCallableRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit HttpsCallableRequest(
    const std::string& region,
    const std::string& function_name,
    int64_t timeout_ms);

  // Constructs an object setting all fields.
  explicit HttpsCallableRequest(
    const std::string* app_name,
    const std::string& region,
    const std::string* origin,
    const std::string& function_name,
    const flutter::EncodableValue* parameters,
    int64_t timeout_ms);

  const std::string* app_name() const;
  void set_app_name(const std::string_view* value_arg);
  void set_app_name(std::string_view value_arg);

  const std::string& region() const;
  void set_region(std::string_view value_arg);

  const std::string* origin() const;
  void set_origin(const std::string_view* value_arg);
  void set_origin(std::string_view value_arg);

  const std::string& function_name() const;
  void set_function_name(std::string_view value_arg);

  const flutter::EncodableValue* parameters() const;
  void set_parameters(const flutter::EncodableValue* value_arg);
  void set_parameters(const flutter::EncodableValue& value_arg);

  int64_t timeout_ms() const;
  void set_timeout_ms(int64_t value_arg);


 private:
  static HttpsCallableRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirebaseFunctionsHostApi;
  friend class FirebaseFunctionsHostApiCodecSerializer;
  std::optional<std::string> app_name_;
  std::string region_;
  std::optional<std::string> origin_;
  std::string function_name_;
  std::optional<flutter::EncodableValue> parameters_;
  int64_t timeout_ms_;

};


// Generated class from Pigeon that represents data sent in messages.
class HttpsCallableResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  HttpsCallableResponse();

  // Constructs an object setting all fields.
  explicit HttpsCallableResponse(const flutter::EncodableValue* data);

  const flutter::EncodableValue* data() const;
  void set_data(const flutter::EncodableValue* value_arg);
  void set_data(const flutter::EncodableValue& value_arg);


 private:
  static HttpsCallableResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirebaseFunctionsHostApi;
  friend class FirebaseFunctionsHostApiCodecSerializer;
  std::optional<flutter::EncodableValue> data_;

};

class FirebaseFunctionsHostApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  FirebaseFunctionsHostApiCodecSerializer();
  inline static FirebaseFunctionsHostApiCodecSerializer& GetInstance() {
    static FirebaseFunctionsHostApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class FirebaseFunctionsHostApi {
 public:
  FirebaseFunctionsHostApi(const FirebaseFunctionsHostApi&) = delete;
  FirebaseFunctionsHostApi& operator=(const FirebaseFunctionsHostApi&) = delete;
  virtual ~FirebaseFunctionsHostApi() {}
  virtual void CallFunction(
    const HttpsCallableRequest& request,
    std::function<void(ErrorOr<HttpsCallableResponse> reply)> result) = 0;
  virtual void UseFunctionsEmulator(
    const std::string& app_name,
    const std::string& region,
    const std::string& host,
    int64_t port,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by FirebaseFunctionsHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `FirebaseFunctionsHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    FirebaseFunctionsHostApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  FirebaseFunctionsHostApi() = default;

};
}  // namespace firebase_functions_webos
#endif  // PIGEON_MESSAGES_G_H_
