// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_storage_webos {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class FirebaseStorageHostApi;
  friend class FirebaseStorageFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class PigeonStringFormat {
  raw = 0,
  base64 = 1,
  base64Url = 2,
  dataUrl = 3
};

// Settable metadata fields for an upload.
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonSettableMetaData {
 public:
  // Constructs an object setting all non-nullable fields.
  PigeonSettableMetaData();

  // Constructs an object setting all fields.
  explicit PigeonSettableMetaData(
    const std::string* cache_control,
    const std::string* content_disposition,
    const std::string* content_encoding,
    const std::string* content_language,
    const std::string* content_type,
    const flutter::EncodableMap* custom_metadata);

  const std::string* cache_control() const;
  void set_cache_control(const std::string_view* value_arg);
  void set_cache_control(std::string_view value_arg);

  const std::string* content_disposition() const;
  void set_content_disposition(const std::string_view* value_arg);
  void set_content_disposition(std::string_view value_arg);

  const std::string* content_encoding() const;
  void set_content_encoding(const std::string_view* value_arg);
  void set_content_encoding(std::string_view value_arg);

  const std::string* content_language() const;
  void set_content_language(const std::string_view* value_arg);
  void set_content_language(std::string_view value_arg);

  const std::string* content_type() const;
  void set_content_type(const std::string_view* value_arg);
  void set_content_type(std::string_view value_arg);

  const flutter::EncodableMap* custom_metadata() const;
  void set_custom_metadata(const flutter::EncodableMap* value_arg);
  void set_custom_metadata(const flutter::EncodableMap& value_arg);


 private:
  static PigeonSettableMetaData FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirebaseStorageHostApi;
  friend class FirebaseStorageHostApiCodecSerializer;
  friend class FirebaseStorageFlutterApi;
  friend class FirebaseStorageFlutterApiCodecSerializer;
  std::optional<std::string> cache_control_;
  std::optional<std::string> content_disposition_;
  std::optional<std::string> content_encoding_;
  std::optional<std::string> content_language_;
  std::optional<std::string> content_type_;
  std::optional<flutter::EncodableMap> custom_metadata_;

};


// Full metadata returned by the server.
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonFullMetaData {
 public:
  // Constructs an object setting all non-nullable fields.
  PigeonFullMetaData();

  // Constructs an object setting all fields.
  explicit PigeonFullMetaData(const flutter::EncodableMap* metadata);

  const flutter::EncodableMap* metadata() const;
  void set_metadata(const flutter::EncodableMap* value_arg);
  void set_metadata(const flutter::EncodableMap& value_arg);


 private:
  static PigeonFullMetaData FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PigeonTaskSnapshot;
  friend class FirebaseStorageHostApi;
  friend class FirebaseStorageHostApiCodecSerializer;
  friend class FirebaseStorageFlutterApi;
  friend class FirebaseStorageFlutterApiCodecSerializer;
  std::optional<flutter::EncodableMap> metadata_;

};


// Options for listing items under a storage reference.
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonListOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  PigeonListOptions();

  // Constructs an object setting all fields.
  explicit PigeonListOptions(
    const int64_t* max_results,
    const std::string* page_token);

  const int64_t* max_results() const;
  void set_max_results(const int64_t* value_arg);
  void set_max_results(int64_t value_arg);

  const std::string* page_token() const;
  void set_page_token(const std::string_view* value_arg);
  void set_page_token(std::string_view value_arg);


 private:
  static PigeonListOptions FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirebaseStorageHostApi;
  friend class FirebaseStorageHostApiCodecSerializer;
  friend class FirebaseStorageFlutterApi;
  friend class FirebaseStorageFlutterApiCodecSerializer;
  std::optional<int64_t> max_results_;
  std::optional<std::string> page_token_;

};


// Result of a list/listAll operation.
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonListResult {
 public:
  // Constructs an object setting all non-nullable fields.
  PigeonListResult();

  // Constructs an object setting all fields.
  explicit PigeonListResult(
    const flutter::EncodableList* items,
    const flutter::EncodableList* prefixs,
    const std::string* page_token);

  const flutter::EncodableList* items() const;
  void set_items(const flutter::EncodableList* value_arg);
  void set_items(const flutter::EncodableList& value_arg);

  const flutter::EncodableList* prefixs() const;
  void set_prefixs(const flutter::EncodableList* value_arg);
  void set_prefixs(const flutter::EncodableList& value_arg);

  const std::string* page_token() const;
  void set_page_token(const std::string_view* value_arg);
  void set_page_token(std::string_view value_arg);


 private:
  static PigeonListResult FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirebaseStorageHostApi;
  friend class FirebaseStorageHostApiCodecSerializer;
  friend class FirebaseStorageFlutterApi;
  friend class FirebaseStorageFlutterApiCodecSerializer;
  std::optional<flutter::EncodableList> items_;
  std::optional<flutter::EncodableList> prefixs_;
  std::optional<std::string> page_token_;

};


// A snapshot of an ongoing transfer task.
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonTaskSnapshot {
 public:
  // Constructs an object setting all non-nullable fields.
  PigeonTaskSnapshot();

  // Constructs an object setting all fields.
  explicit PigeonTaskSnapshot(
    const std::string* handle,
    const int64_t* bytes_transferred,
    const int64_t* total_bytes,
    const int64_t* state,
    const PigeonFullMetaData* metadata);

  ~PigeonTaskSnapshot() = default;
  PigeonTaskSnapshot(const PigeonTaskSnapshot& other);
  PigeonTaskSnapshot& operator=(const PigeonTaskSnapshot& other);
  PigeonTaskSnapshot(PigeonTaskSnapshot&& other) = default;
  PigeonTaskSnapshot& operator=(PigeonTaskSnapshot&& other) noexcept = default;
  const std::string* handle() const;
  void set_handle(const std::string_view* value_arg);
  void set_handle(std::string_view value_arg);

  const int64_t* bytes_transferred() const;
  void set_bytes_transferred(const int64_t* value_arg);
  void set_bytes_transferred(int64_t value_arg);

  const int64_t* total_bytes() const;
  void set_total_bytes(const int64_t* value_arg);
  void set_total_bytes(int64_t value_arg);

  // 0 = paused, 1 = running, 2 = success, 3 = canceled, 4 = error
  const int64_t* state() const;
  void set_state(const int64_t* value_arg);
  void set_state(int64_t value_arg);

  const PigeonFullMetaData* metadata() const;
  void set_metadata(const PigeonFullMetaData* value_arg);
  void set_metadata(const PigeonFullMetaData& value_arg);


 private:
  static PigeonTaskSnapshot FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirebaseStorageHostApi;
  friend class FirebaseStorageHostApiCodecSerializer;
  friend class FirebaseStorageFlutterApi;
  friend class FirebaseStorageFlutterApiCodecSerializer;
  std::optional<std::string> handle_;
  std::optional<int64_t> bytes_transferred_;
  std::optional<int64_t> total_bytes_;
  std::optional<int64_t> state_;
  std::unique_ptr<PigeonFullMetaData> metadata_;

};

class FirebaseStorageHostApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  FirebaseStorageHostApiCodecSerializer();
  inline static FirebaseStorageHostApiCodecSerializer& GetInstance() {
    static FirebaseStorageHostApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class FirebaseStorageHostApi {
 public:
  FirebaseStorageHostApi(const FirebaseStorageHostApi&) = delete;
  FirebaseStorageHostApi& operator=(const FirebaseStorageHostApi&) = delete;
  virtual ~FirebaseStorageHostApi() {}
  virtual void SetMaxOperationRetryTime(
    const std::string& app_name,
    const std::string& bucket,
    int64_t time,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetMaxUploadRetryTime(
    const std::string& app_name,
    const std::string& bucket,
    int64_t time,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetMaxDownloadRetryTime(
    const std::string& app_name,
    const std::string& bucket,
    int64_t time,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void UseStorageEmulator(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& host,
    int64_t port,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void ReferenceGetDownloadURL(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual void ReferenceGetMetaData(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    std::function<void(ErrorOr<PigeonFullMetaData> reply)> result) = 0;
  virtual void ReferenceUpdateMetaData(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    const PigeonSettableMetaData& metadata,
    std::function<void(ErrorOr<PigeonFullMetaData> reply)> result) = 0;
  virtual void ReferenceDelete(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void ReferenceList(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    const PigeonListOptions& options,
    std::function<void(ErrorOr<PigeonListResult> reply)> result) = 0;
  virtual void ReferenceListAll(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    std::function<void(ErrorOr<PigeonListResult> reply)> result) = 0;
  virtual void TaskStartPutData(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    const PigeonSettableMetaData* metadata,
    const std::vector<uint8_t>& data,
    const std::string& handle,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void TaskStartPutString(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    const std::string& data,
    const PigeonStringFormat& format,
    const PigeonSettableMetaData* metadata,
    const std::string& handle,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void TaskStartPutFile(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    const std::string& file_path,
    const PigeonSettableMetaData* metadata,
    const std::string& handle,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void TaskStartWriteToFile(
    const std::string& app_name,
    const std::string& bucket,
    const std::string& path,
    const std::string& file_path,
    const std::string& handle,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void TaskPause(
    const std::string& handle,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void TaskResume(
    const std::string& handle,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void TaskCancel(
    const std::string& handle,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by FirebaseStorageHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `FirebaseStorageHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    FirebaseStorageHostApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  FirebaseStorageHostApi() = default;

};
class FirebaseStorageFlutterApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  FirebaseStorageFlutterApiCodecSerializer();
  inline static FirebaseStorageFlutterApiCodecSerializer& GetInstance() {
    static FirebaseStorageFlutterApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class FirebaseStorageFlutterApi {
 public:
  FirebaseStorageFlutterApi(flutter::BinaryMessenger* binary_messenger);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnTaskEvent(
    const std::string& handle,
    const PigeonTaskSnapshot& snapshot,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnTaskError(
    const std::string& handle,
    int64_t error_code,
    const std::string& message,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
};

}  // namespace firebase_storage_webos
#endif  // PIGEON_MESSAGES_G_H_
