name: shared_preferences_webos_example
description: Demonstrates how to use the shared_preferences_webos plugin.
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  shared_preferences_webos:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
