// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_auth_webos {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class FirebaseAuthHostApi;
  friend class FirebaseAuthFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// User info from a provider (e.g. Google, email)
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonUserInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PigeonUserInfo(
    const std::string& uid,
    const std::string& provider_id,
    bool is_email_verified,
    bool is_anonymous);

  // Constructs an object setting all fields.
  explicit PigeonUserInfo(
    const std::string& uid,
    const std::string& provider_id,
    const std::string* email,
    const std::string* display_name,
    const std::string* photo_url,
    const std::string* phone_number,
    bool is_email_verified,
    bool is_anonymous);

  const std::string& uid() const;
  void set_uid(std::string_view value_arg);

  const std::string& provider_id() const;
  void set_provider_id(std::string_view value_arg);

  const std::string* email() const;
  void set_email(const std::string_view* value_arg);
  void set_email(std::string_view value_arg);

  const std::string* display_name() const;
  void set_display_name(const std::string_view* value_arg);
  void set_display_name(std::string_view value_arg);

  const std::string* photo_url() const;
  void set_photo_url(const std::string_view* value_arg);
  void set_photo_url(std::string_view value_arg);

  const std::string* phone_number() const;
  void set_phone_number(const std::string_view* value_arg);
  void set_phone_number(std::string_view value_arg);

  bool is_email_verified() const;
  void set_is_email_verified(bool value_arg);

  bool is_anonymous() const;
  void set_is_anonymous(bool value_arg);


 private:
  static PigeonUserInfo FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PigeonUserDetails;
  friend class FirebaseAuthHostApi;
  friend class FirebaseAuthHostApiCodecSerializer;
  friend class FirebaseAuthFlutterApi;
  friend class FirebaseAuthFlutterApiCodecSerializer;
  std::string uid_;
  std::string provider_id_;
  std::optional<std::string> email_;
  std::optional<std::string> display_name_;
  std::optional<std::string> photo_url_;
  std::optional<std::string> phone_number_;
  bool is_email_verified_;
  bool is_anonymous_;

};


// Core user details returned for every auth operation
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonUserDetails {
 public:
  // Constructs an object setting all fields.
  explicit PigeonUserDetails(
    const PigeonUserInfo& user_info,
    const flutter::EncodableList& provider_data);

  ~PigeonUserDetails() = default;
  PigeonUserDetails(const PigeonUserDetails& other);
  PigeonUserDetails& operator=(const PigeonUserDetails& other);
  PigeonUserDetails(PigeonUserDetails&& other) = default;
  PigeonUserDetails& operator=(PigeonUserDetails&& other) noexcept = default;
  const PigeonUserInfo& user_info() const;
  void set_user_info(const PigeonUserInfo& value_arg);

  const flutter::EncodableList& provider_data() const;
  void set_provider_data(const flutter::EncodableList& value_arg);


 private:
  static PigeonUserDetails FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirebaseAuthHostApi;
  friend class FirebaseAuthHostApiCodecSerializer;
  friend class FirebaseAuthFlutterApi;
  friend class FirebaseAuthFlutterApiCodecSerializer;
  std::unique_ptr<PigeonUserInfo> user_info_;
  flutter::EncodableList provider_data_;

};

class FirebaseAuthHostApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  FirebaseAuthHostApiCodecSerializer();
  inline static FirebaseAuthHostApiCodecSerializer& GetInstance() {
    static FirebaseAuthHostApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class FirebaseAuthHostApi {
 public:
  FirebaseAuthHostApi(const FirebaseAuthHostApi&) = delete;
  FirebaseAuthHostApi& operator=(const FirebaseAuthHostApi&) = delete;
  virtual ~FirebaseAuthHostApi() {}
  // Sign in with email + password
  virtual void SignInWithEmailAndPassword(
    const std::string& app_name,
    const std::string& email,
    const std::string& password,
    std::function<void(ErrorOr<PigeonUserDetails> reply)> result) = 0;
  // Create account with email + password
  virtual void CreateUserWithEmailAndPassword(
    const std::string& app_name,
    const std::string& email,
    const std::string& password,
    std::function<void(ErrorOr<PigeonUserDetails> reply)> result) = 0;
  // Sign in anonymously
  virtual void SignInAnonymously(
    const std::string& app_name,
    std::function<void(ErrorOr<PigeonUserDetails> reply)> result) = 0;
  // Sign out the current user
  virtual void SignOut(
    const std::string& app_name,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SignInWithCustomToken(
    const std::string& app_name,
    const std::string& token,
    std::function<void(ErrorOr<PigeonUserDetails> reply)> result) = 0;
  virtual void GetIdToken(
    const std::string& app_name,
    bool force_refresh,
    std::function<void(ErrorOr<std::string> reply)> result) = 0;
  // Update user profile (display name and/or photo URL)
  virtual void UpdateUserProfile(
    const std::string& app_name,
    const std::string* display_name,
    const std::string* photo_url,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Send email verification to current user
  virtual void SendEmailVerification(
    const std::string& app_name,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Send password reset email
  virtual void SendPasswordResetEmail(
    const std::string& app_name,
    const std::string& email,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Update user password
  virtual void UpdatePassword(
    const std::string& app_name,
    const std::string& new_password,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Reload user data from server
  virtual void Reload(
    const std::string& app_name,
    std::function<void(ErrorOr<PigeonUserDetails> reply)> result) = 0;
  // Delete user account
  virtual void Delete(
    const std::string& app_name,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Configure Firebase Auth emulator
  virtual void UseAuthEmulator(
    const std::string& app_name,
    const std::string& host,
    int64_t port,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by FirebaseAuthHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `FirebaseAuthHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    FirebaseAuthHostApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  FirebaseAuthHostApi() = default;

};
class FirebaseAuthFlutterApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  FirebaseAuthFlutterApiCodecSerializer();
  inline static FirebaseAuthFlutterApiCodecSerializer& GetInstance() {
    static FirebaseAuthFlutterApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class FirebaseAuthFlutterApi {
 public:
  FirebaseAuthFlutterApi(flutter::BinaryMessenger* binary_messenger);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnAuthStateChanged(
    const std::string& app_name,
    const PigeonUserDetails* user,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnIdTokenChanged(
    const std::string& app_name,
    const PigeonUserDetails* user,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnUserChanged(
    const std::string& app_name,
    const PigeonUserDetails* user,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
};

}  // namespace firebase_auth_webos
#endif  // PIGEON_MESSAGES_G_H_
