// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_auth_webos {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// PigeonUserInfo

PigeonUserInfo::PigeonUserInfo(
  const std::string& uid,
  const std::string& provider_id,
  bool is_email_verified,
  bool is_anonymous)
 : uid_(uid),
    provider_id_(provider_id),
    is_email_verified_(is_email_verified),
    is_anonymous_(is_anonymous) {}

PigeonUserInfo::PigeonUserInfo(
  const std::string& uid,
  const std::string& provider_id,
  const std::string* email,
  const std::string* display_name,
  const std::string* photo_url,
  const std::string* phone_number,
  bool is_email_verified,
  bool is_anonymous)
 : uid_(uid),
    provider_id_(provider_id),
    email_(email ? std::optional<std::string>(*email) : std::nullopt),
    display_name_(display_name ? std::optional<std::string>(*display_name) : std::nullopt),
    photo_url_(photo_url ? std::optional<std::string>(*photo_url) : std::nullopt),
    phone_number_(phone_number ? std::optional<std::string>(*phone_number) : std::nullopt),
    is_email_verified_(is_email_verified),
    is_anonymous_(is_anonymous) {}

const std::string& PigeonUserInfo::uid() const {
  return uid_;
}

void PigeonUserInfo::set_uid(std::string_view value_arg) {
  uid_ = value_arg;
}


const std::string& PigeonUserInfo::provider_id() const {
  return provider_id_;
}

void PigeonUserInfo::set_provider_id(std::string_view value_arg) {
  provider_id_ = value_arg;
}


const std::string* PigeonUserInfo::email() const {
  return email_ ? &(*email_) : nullptr;
}

void PigeonUserInfo::set_email(const std::string_view* value_arg) {
  email_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonUserInfo::set_email(std::string_view value_arg) {
  email_ = value_arg;
}


const std::string* PigeonUserInfo::display_name() const {
  return display_name_ ? &(*display_name_) : nullptr;
}

void PigeonUserInfo::set_display_name(const std::string_view* value_arg) {
  display_name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonUserInfo::set_display_name(std::string_view value_arg) {
  display_name_ = value_arg;
}


const std::string* PigeonUserInfo::photo_url() const {
  return photo_url_ ? &(*photo_url_) : nullptr;
}

void PigeonUserInfo::set_photo_url(const std::string_view* value_arg) {
  photo_url_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonUserInfo::set_photo_url(std::string_view value_arg) {
  photo_url_ = value_arg;
}


const std::string* PigeonUserInfo::phone_number() const {
  return phone_number_ ? &(*phone_number_) : nullptr;
}

void PigeonUserInfo::set_phone_number(const std::string_view* value_arg) {
  phone_number_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonUserInfo::set_phone_number(std::string_view value_arg) {
  phone_number_ = value_arg;
}


bool PigeonUserInfo::is_email_verified() const {
  return is_email_verified_;
}

void PigeonUserInfo::set_is_email_verified(bool value_arg) {
  is_email_verified_ = value_arg;
}


bool PigeonUserInfo::is_anonymous() const {
  return is_anonymous_;
}

void PigeonUserInfo::set_is_anonymous(bool value_arg) {
  is_anonymous_ = value_arg;
}


EncodableList PigeonUserInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(EncodableValue(uid_));
  list.push_back(EncodableValue(provider_id_));
  list.push_back(email_ ? EncodableValue(*email_) : EncodableValue());
  list.push_back(display_name_ ? EncodableValue(*display_name_) : EncodableValue());
  list.push_back(photo_url_ ? EncodableValue(*photo_url_) : EncodableValue());
  list.push_back(phone_number_ ? EncodableValue(*phone_number_) : EncodableValue());
  list.push_back(EncodableValue(is_email_verified_));
  list.push_back(EncodableValue(is_anonymous_));
  return list;
}

PigeonUserInfo PigeonUserInfo::FromEncodableList(const EncodableList& list) {
  PigeonUserInfo decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<bool>(list[6]),
    std::get<bool>(list[7]));
  auto& encodable_email = list[2];
  if (!encodable_email.IsNull()) {
    decoded.set_email(std::get<std::string>(encodable_email));
  }
  auto& encodable_display_name = list[3];
  if (!encodable_display_name.IsNull()) {
    decoded.set_display_name(std::get<std::string>(encodable_display_name));
  }
  auto& encodable_photo_url = list[4];
  if (!encodable_photo_url.IsNull()) {
    decoded.set_photo_url(std::get<std::string>(encodable_photo_url));
  }
  auto& encodable_phone_number = list[5];
  if (!encodable_phone_number.IsNull()) {
    decoded.set_phone_number(std::get<std::string>(encodable_phone_number));
  }
  return decoded;
}

// PigeonUserDetails

PigeonUserDetails::PigeonUserDetails(
  const PigeonUserInfo& user_info,
  const EncodableList& provider_data)
 : user_info_(std::make_unique<PigeonUserInfo>(user_info)),
    provider_data_(provider_data) {}

PigeonUserDetails::PigeonUserDetails(const PigeonUserDetails& other)
 : user_info_(std::make_unique<PigeonUserInfo>(*other.user_info_)),
    provider_data_(other.provider_data_) {}

PigeonUserDetails& PigeonUserDetails::operator=(const PigeonUserDetails& other) {
  user_info_ = std::make_unique<PigeonUserInfo>(*other.user_info_);
  provider_data_ = other.provider_data_;
  return *this;
}

const PigeonUserInfo& PigeonUserDetails::user_info() const {
  return *user_info_;
}

void PigeonUserDetails::set_user_info(const PigeonUserInfo& value_arg) {
  user_info_ = std::make_unique<PigeonUserInfo>(value_arg);
}


const EncodableList& PigeonUserDetails::provider_data() const {
  return provider_data_;
}

void PigeonUserDetails::set_provider_data(const EncodableList& value_arg) {
  provider_data_ = value_arg;
}


EncodableList PigeonUserDetails::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(user_info_->ToEncodableList()));
  list.push_back(EncodableValue(provider_data_));
  return list;
}

PigeonUserDetails PigeonUserDetails::FromEncodableList(const EncodableList& list) {
  PigeonUserDetails decoded(
    PigeonUserInfo::FromEncodableList(std::get<EncodableList>(list[0])),
    std::get<EncodableList>(list[1]));
  return decoded;
}


FirebaseAuthHostApiCodecSerializer::FirebaseAuthHostApiCodecSerializer() {}

EncodableValue FirebaseAuthHostApiCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 128:
      return CustomEncodableValue(PigeonUserDetails::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 129:
      return CustomEncodableValue(PigeonUserInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 130:
      return CustomEncodableValue(PigeonUserInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
  }
}

void FirebaseAuthHostApiCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(PigeonUserDetails)) {
      stream->WriteByte(128);
      WriteValue(EncodableValue(std::any_cast<PigeonUserDetails>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonUserInfo)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<PigeonUserInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonUserInfo)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<PigeonUserInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FirebaseAuthHostApi.
const flutter::StandardMessageCodec& FirebaseAuthHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&FirebaseAuthHostApiCodecSerializer::GetInstance());
}

// Sets up an instance of `FirebaseAuthHostApi` to handle messages through the `binary_messenger`.
void FirebaseAuthHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FirebaseAuthHostApi* api) {
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.signInWithEmailAndPassword", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_email_arg = args.at(1);
          if (encodable_email_arg.IsNull()) {
            reply(WrapError("email_arg unexpectedly null."));
            return;
          }
          const auto& email_arg = std::get<std::string>(encodable_email_arg);
          const auto& encodable_password_arg = args.at(2);
          if (encodable_password_arg.IsNull()) {
            reply(WrapError("password_arg unexpectedly null."));
            return;
          }
          const auto& password_arg = std::get<std::string>(encodable_password_arg);
          api->SignInWithEmailAndPassword(app_name_arg, email_arg, password_arg, [reply](ErrorOr<PigeonUserDetails>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.createUserWithEmailAndPassword", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_email_arg = args.at(1);
          if (encodable_email_arg.IsNull()) {
            reply(WrapError("email_arg unexpectedly null."));
            return;
          }
          const auto& email_arg = std::get<std::string>(encodable_email_arg);
          const auto& encodable_password_arg = args.at(2);
          if (encodable_password_arg.IsNull()) {
            reply(WrapError("password_arg unexpectedly null."));
            return;
          }
          const auto& password_arg = std::get<std::string>(encodable_password_arg);
          api->CreateUserWithEmailAndPassword(app_name_arg, email_arg, password_arg, [reply](ErrorOr<PigeonUserDetails>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.signInAnonymously", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          api->SignInAnonymously(app_name_arg, [reply](ErrorOr<PigeonUserDetails>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.signOut", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          api->SignOut(app_name_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.signInWithCustomToken", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_token_arg = args.at(1);
          if (encodable_token_arg.IsNull()) {
            reply(WrapError("token_arg unexpectedly null."));
            return;
          }
          const auto& token_arg = std::get<std::string>(encodable_token_arg);
          api->SignInWithCustomToken(app_name_arg, token_arg, [reply](ErrorOr<PigeonUserDetails>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.getIdToken", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_force_refresh_arg = args.at(1);
          if (encodable_force_refresh_arg.IsNull()) {
            reply(WrapError("force_refresh_arg unexpectedly null."));
            return;
          }
          const auto& force_refresh_arg = std::get<bool>(encodable_force_refresh_arg);
          api->GetIdToken(app_name_arg, force_refresh_arg, [reply](ErrorOr<std::string>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.updateUserProfile", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_display_name_arg = args.at(1);
          const auto* display_name_arg = std::get_if<std::string>(&encodable_display_name_arg);
          const auto& encodable_photo_url_arg = args.at(2);
          const auto* photo_url_arg = std::get_if<std::string>(&encodable_photo_url_arg);
          api->UpdateUserProfile(app_name_arg, display_name_arg, photo_url_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.sendEmailVerification", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          api->SendEmailVerification(app_name_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.sendPasswordResetEmail", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_email_arg = args.at(1);
          if (encodable_email_arg.IsNull()) {
            reply(WrapError("email_arg unexpectedly null."));
            return;
          }
          const auto& email_arg = std::get<std::string>(encodable_email_arg);
          api->SendPasswordResetEmail(app_name_arg, email_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.updatePassword", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_new_password_arg = args.at(1);
          if (encodable_new_password_arg.IsNull()) {
            reply(WrapError("new_password_arg unexpectedly null."));
            return;
          }
          const auto& new_password_arg = std::get<std::string>(encodable_new_password_arg);
          api->UpdatePassword(app_name_arg, new_password_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.reload", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          api->Reload(app_name_arg, [reply](ErrorOr<PigeonUserDetails>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.delete", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          api->Delete(app_name_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthHostApi.useAuthEmulator", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_host_arg = args.at(1);
          if (encodable_host_arg.IsNull()) {
            reply(WrapError("host_arg unexpectedly null."));
            return;
          }
          const auto& host_arg = std::get<std::string>(encodable_host_arg);
          const auto& encodable_port_arg = args.at(2);
          if (encodable_port_arg.IsNull()) {
            reply(WrapError("port_arg unexpectedly null."));
            return;
          }
          const int64_t port_arg = encodable_port_arg.LongValue();
          api->UseAuthEmulator(app_name_arg, host_arg, port_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FirebaseAuthHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FirebaseAuthHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}


FirebaseAuthFlutterApiCodecSerializer::FirebaseAuthFlutterApiCodecSerializer() {}

EncodableValue FirebaseAuthFlutterApiCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 128:
      return CustomEncodableValue(PigeonUserDetails::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 129:
      return CustomEncodableValue(PigeonUserInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 130:
      return CustomEncodableValue(PigeonUserInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
  }
}

void FirebaseAuthFlutterApiCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(PigeonUserDetails)) {
      stream->WriteByte(128);
      WriteValue(EncodableValue(std::any_cast<PigeonUserDetails>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonUserInfo)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<PigeonUserInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonUserInfo)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<PigeonUserInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
FirebaseAuthFlutterApi::FirebaseAuthFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger) {}

const flutter::StandardMessageCodec& FirebaseAuthFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&FirebaseAuthFlutterApiCodecSerializer::GetInstance());
}

void FirebaseAuthFlutterApi::OnAuthStateChanged(
  const std::string& app_name_arg,
  const PigeonUserDetails* user_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthFlutterApi.onAuthStateChanged";
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(app_name_arg),
    user_arg ? CustomEncodableValue(*user_arg) : EncodableValue(),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void FirebaseAuthFlutterApi::OnIdTokenChanged(
  const std::string& app_name_arg,
  const PigeonUserDetails* user_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthFlutterApi.onIdTokenChanged";
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(app_name_arg),
    user_arg ? CustomEncodableValue(*user_arg) : EncodableValue(),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void FirebaseAuthFlutterApi::OnUserChanged(
  const std::string& app_name_arg,
  const PigeonUserDetails* user_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.firebase_auth_webos.FirebaseAuthFlutterApi.onUserChanged";
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(app_name_arg),
    user_arg ? CustomEncodableValue(*user_arg) : EncodableValue(),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace firebase_auth_webos
