#pragma once

#include <flutter/plugin_registrar.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <map>
#include <memory>
#include <mutex>
#include <string>
#include <vector>

#include "messages.g.h"   // generated by: dart run pigeon --input pigeon/messages.dart
#include <firebase/app.h>
#include <firebase/storage.h>

namespace firebase_storage_webos {

class StorageTaskListener;

class FirebaseStorageWebosPlugin : public flutter::Plugin,
                                   public FirebaseStorageHostApi {
 public:
  static void RegisterWithRegistrar(flutter::PluginRegistrar* registrar);

  explicit FirebaseStorageWebosPlugin(flutter::BinaryMessenger* messenger);
  virtual ~FirebaseStorageWebosPlugin();

  FirebaseStorageWebosPlugin(const FirebaseStorageWebosPlugin&) = delete;
  FirebaseStorageWebosPlugin& operator=(const FirebaseStorageWebosPlugin&) = delete;

  void SetMaxOperationRetryTime(const std::string& app_name,
                                 const std::string& bucket,
                                 int64_t time,
                                 std::function<void(std::optional<FlutterError>)> result) override;

  void SetMaxUploadRetryTime(const std::string& app_name,
                              const std::string& bucket,
                              int64_t time,
                              std::function<void(std::optional<FlutterError>)> result) override;

  void SetMaxDownloadRetryTime(const std::string& app_name,
                                const std::string& bucket,
                                int64_t time,
                                std::function<void(std::optional<FlutterError>)> result) override;

  void UseStorageEmulator(const std::string& app_name,
                           const std::string& bucket,
                           const std::string& host,
                           int64_t port,
                           std::function<void(std::optional<FlutterError>)> result) override;

  void ReferenceGetDownloadURL(const std::string& app_name,
                                const std::string& bucket,
                                const std::string& path,
                                std::function<void(ErrorOr<std::string>)> result) override;

  void ReferenceGetMetaData(const std::string& app_name,
                             const std::string& bucket,
                             const std::string& path,
                             std::function<void(ErrorOr<PigeonFullMetaData>)> result) override;

  void ReferenceUpdateMetaData(const std::string& app_name,
                                const std::string& bucket,
                                const std::string& path,
                                const PigeonSettableMetaData& metadata,
                                std::function<void(ErrorOr<PigeonFullMetaData>)> result) override;

  void ReferenceDelete(const std::string& app_name,
                        const std::string& bucket,
                        const std::string& path,
                        std::function<void(std::optional<FlutterError>)> result) override;

  void ReferenceGetData(const std::string& app_name,
                        const std::string& bucket,
                        const std::string& path,
                        int64_t max_size,
                        std::function<void(ErrorOr<std::vector<uint8_t>>)> result) override;

  void ReferenceList(const std::string& app_name,
                      const std::string& bucket,
                      const std::string& path,
                      const PigeonListOptions& options,
                      std::function<void(ErrorOr<PigeonListResult>)> result) override;

  void ReferenceListAll(const std::string& app_name,
                         const std::string& bucket,
                         const std::string& path,
                         std::function<void(ErrorOr<PigeonListResult>)> result) override;

  void TaskStartPutData(const std::string& app_name,
                         const std::string& bucket,
                         const std::string& path,
                         const PigeonSettableMetaData* metadata,
                         const std::vector<uint8_t>& data,
                         const std::string& handle,
                         std::function<void(std::optional<FlutterError>)> result) override;

  void TaskStartPutString(const std::string& app_name,
                           const std::string& bucket,
                           const std::string& path,
                           const std::string& data,
                           const PigeonStringFormat& format,
                           const PigeonSettableMetaData* metadata,
                           const std::string& handle,
                           std::function<void(std::optional<FlutterError>)> result) override;

  void TaskStartPutFile(const std::string& app_name,
                         const std::string& bucket,
                         const std::string& path,
                         const std::string& file_path,
                         const PigeonSettableMetaData* metadata,
                         const std::string& handle,
                         std::function<void(std::optional<FlutterError>)> result) override;

  void TaskStartWriteToFile(const std::string& app_name,
                             const std::string& bucket,
                             const std::string& path,
                             const std::string& file_path,
                             const std::string& handle,
                             std::function<void(std::optional<FlutterError>)> result) override;

  void TaskPause(const std::string& handle,
                  std::function<void(std::optional<FlutterError>)> result) override;

  void TaskResume(const std::string& handle,
                   std::function<void(std::optional<FlutterError>)> result) override;

  void TaskCancel(const std::string& handle,
                   std::function<void(std::optional<FlutterError>)> result) override;

  void NotifyTaskEvent(const std::string& handle,
                       int64_t bytes_transferred,
                       int64_t total_bytes,
                       int state_index,
                       const firebase::storage::Metadata* metadata = nullptr);
  void NotifyTaskError(const std::string& handle,
                       int error_code,
                       const std::string& message);

 private:
  firebase::storage::Storage* GetStorage(const std::string& app_name,
                                          const std::string& bucket);
  firebase::storage::StorageReference GetRef(
      firebase::storage::Storage* storage, const std::string& path);

  firebase::storage::Metadata PigeonToNativeMetadata(
      const PigeonSettableMetaData& p);
  PigeonFullMetaData NativeMetadataToPigeon(
      const firebase::storage::Metadata& m);

  struct TaskData {
    firebase::storage::Controller controller;
  
    std::unique_ptr<StorageTaskListener> listener;
  
    std::vector<uint8_t> buffer;
  };

  flutter::BinaryMessenger* messenger_;
  std::unique_ptr<FirebaseStorageFlutterApi> flutter_api_;

  std::mutex tasks_mutex_;
  std::map<std::string, TaskData> tasks_;
};

}  // namespace firebase_storage_webos

