// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_storage_webos {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// PigeonSettableMetaData

PigeonSettableMetaData::PigeonSettableMetaData() {}

PigeonSettableMetaData::PigeonSettableMetaData(
  const std::string* cache_control,
  const std::string* content_disposition,
  const std::string* content_encoding,
  const std::string* content_language,
  const std::string* content_type,
  const EncodableMap* custom_metadata)
 : cache_control_(cache_control ? std::optional<std::string>(*cache_control) : std::nullopt),
    content_disposition_(content_disposition ? std::optional<std::string>(*content_disposition) : std::nullopt),
    content_encoding_(content_encoding ? std::optional<std::string>(*content_encoding) : std::nullopt),
    content_language_(content_language ? std::optional<std::string>(*content_language) : std::nullopt),
    content_type_(content_type ? std::optional<std::string>(*content_type) : std::nullopt),
    custom_metadata_(custom_metadata ? std::optional<EncodableMap>(*custom_metadata) : std::nullopt) {}

const std::string* PigeonSettableMetaData::cache_control() const {
  return cache_control_ ? &(*cache_control_) : nullptr;
}

void PigeonSettableMetaData::set_cache_control(const std::string_view* value_arg) {
  cache_control_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonSettableMetaData::set_cache_control(std::string_view value_arg) {
  cache_control_ = value_arg;
}


const std::string* PigeonSettableMetaData::content_disposition() const {
  return content_disposition_ ? &(*content_disposition_) : nullptr;
}

void PigeonSettableMetaData::set_content_disposition(const std::string_view* value_arg) {
  content_disposition_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonSettableMetaData::set_content_disposition(std::string_view value_arg) {
  content_disposition_ = value_arg;
}


const std::string* PigeonSettableMetaData::content_encoding() const {
  return content_encoding_ ? &(*content_encoding_) : nullptr;
}

void PigeonSettableMetaData::set_content_encoding(const std::string_view* value_arg) {
  content_encoding_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonSettableMetaData::set_content_encoding(std::string_view value_arg) {
  content_encoding_ = value_arg;
}


const std::string* PigeonSettableMetaData::content_language() const {
  return content_language_ ? &(*content_language_) : nullptr;
}

void PigeonSettableMetaData::set_content_language(const std::string_view* value_arg) {
  content_language_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonSettableMetaData::set_content_language(std::string_view value_arg) {
  content_language_ = value_arg;
}


const std::string* PigeonSettableMetaData::content_type() const {
  return content_type_ ? &(*content_type_) : nullptr;
}

void PigeonSettableMetaData::set_content_type(const std::string_view* value_arg) {
  content_type_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonSettableMetaData::set_content_type(std::string_view value_arg) {
  content_type_ = value_arg;
}


const EncodableMap* PigeonSettableMetaData::custom_metadata() const {
  return custom_metadata_ ? &(*custom_metadata_) : nullptr;
}

void PigeonSettableMetaData::set_custom_metadata(const EncodableMap* value_arg) {
  custom_metadata_ = value_arg ? std::optional<EncodableMap>(*value_arg) : std::nullopt;
}

void PigeonSettableMetaData::set_custom_metadata(const EncodableMap& value_arg) {
  custom_metadata_ = value_arg;
}


EncodableList PigeonSettableMetaData::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(cache_control_ ? EncodableValue(*cache_control_) : EncodableValue());
  list.push_back(content_disposition_ ? EncodableValue(*content_disposition_) : EncodableValue());
  list.push_back(content_encoding_ ? EncodableValue(*content_encoding_) : EncodableValue());
  list.push_back(content_language_ ? EncodableValue(*content_language_) : EncodableValue());
  list.push_back(content_type_ ? EncodableValue(*content_type_) : EncodableValue());
  list.push_back(custom_metadata_ ? EncodableValue(*custom_metadata_) : EncodableValue());
  return list;
}

PigeonSettableMetaData PigeonSettableMetaData::FromEncodableList(const EncodableList& list) {
  PigeonSettableMetaData decoded;
  auto& encodable_cache_control = list[0];
  if (!encodable_cache_control.IsNull()) {
    decoded.set_cache_control(std::get<std::string>(encodable_cache_control));
  }
  auto& encodable_content_disposition = list[1];
  if (!encodable_content_disposition.IsNull()) {
    decoded.set_content_disposition(std::get<std::string>(encodable_content_disposition));
  }
  auto& encodable_content_encoding = list[2];
  if (!encodable_content_encoding.IsNull()) {
    decoded.set_content_encoding(std::get<std::string>(encodable_content_encoding));
  }
  auto& encodable_content_language = list[3];
  if (!encodable_content_language.IsNull()) {
    decoded.set_content_language(std::get<std::string>(encodable_content_language));
  }
  auto& encodable_content_type = list[4];
  if (!encodable_content_type.IsNull()) {
    decoded.set_content_type(std::get<std::string>(encodable_content_type));
  }
  auto& encodable_custom_metadata = list[5];
  if (!encodable_custom_metadata.IsNull()) {
    decoded.set_custom_metadata(std::get<EncodableMap>(encodable_custom_metadata));
  }
  return decoded;
}

// PigeonFullMetaData

PigeonFullMetaData::PigeonFullMetaData() {}

PigeonFullMetaData::PigeonFullMetaData(const EncodableMap* metadata)
 : metadata_(metadata ? std::optional<EncodableMap>(*metadata) : std::nullopt) {}

const EncodableMap* PigeonFullMetaData::metadata() const {
  return metadata_ ? &(*metadata_) : nullptr;
}

void PigeonFullMetaData::set_metadata(const EncodableMap* value_arg) {
  metadata_ = value_arg ? std::optional<EncodableMap>(*value_arg) : std::nullopt;
}

void PigeonFullMetaData::set_metadata(const EncodableMap& value_arg) {
  metadata_ = value_arg;
}


EncodableList PigeonFullMetaData::ToEncodableList() const {
  EncodableList list;
  list.reserve(1);
  list.push_back(metadata_ ? EncodableValue(*metadata_) : EncodableValue());
  return list;
}

PigeonFullMetaData PigeonFullMetaData::FromEncodableList(const EncodableList& list) {
  PigeonFullMetaData decoded;
  auto& encodable_metadata = list[0];
  if (!encodable_metadata.IsNull()) {
    decoded.set_metadata(std::get<EncodableMap>(encodable_metadata));
  }
  return decoded;
}

// PigeonListOptions

PigeonListOptions::PigeonListOptions() {}

PigeonListOptions::PigeonListOptions(
  const int64_t* max_results,
  const std::string* page_token)
 : max_results_(max_results ? std::optional<int64_t>(*max_results) : std::nullopt),
    page_token_(page_token ? std::optional<std::string>(*page_token) : std::nullopt) {}

const int64_t* PigeonListOptions::max_results() const {
  return max_results_ ? &(*max_results_) : nullptr;
}

void PigeonListOptions::set_max_results(const int64_t* value_arg) {
  max_results_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PigeonListOptions::set_max_results(int64_t value_arg) {
  max_results_ = value_arg;
}


const std::string* PigeonListOptions::page_token() const {
  return page_token_ ? &(*page_token_) : nullptr;
}

void PigeonListOptions::set_page_token(const std::string_view* value_arg) {
  page_token_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonListOptions::set_page_token(std::string_view value_arg) {
  page_token_ = value_arg;
}


EncodableList PigeonListOptions::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(max_results_ ? EncodableValue(*max_results_) : EncodableValue());
  list.push_back(page_token_ ? EncodableValue(*page_token_) : EncodableValue());
  return list;
}

PigeonListOptions PigeonListOptions::FromEncodableList(const EncodableList& list) {
  PigeonListOptions decoded;
  auto& encodable_max_results = list[0];
  if (!encodable_max_results.IsNull()) {
    decoded.set_max_results(encodable_max_results.LongValue());
  }
  auto& encodable_page_token = list[1];
  if (!encodable_page_token.IsNull()) {
    decoded.set_page_token(std::get<std::string>(encodable_page_token));
  }
  return decoded;
}

// PigeonListResult

PigeonListResult::PigeonListResult() {}

PigeonListResult::PigeonListResult(
  const EncodableList* items,
  const EncodableList* prefixs,
  const std::string* page_token)
 : items_(items ? std::optional<EncodableList>(*items) : std::nullopt),
    prefixs_(prefixs ? std::optional<EncodableList>(*prefixs) : std::nullopt),
    page_token_(page_token ? std::optional<std::string>(*page_token) : std::nullopt) {}

const EncodableList* PigeonListResult::items() const {
  return items_ ? &(*items_) : nullptr;
}

void PigeonListResult::set_items(const EncodableList* value_arg) {
  items_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonListResult::set_items(const EncodableList& value_arg) {
  items_ = value_arg;
}


const EncodableList* PigeonListResult::prefixs() const {
  return prefixs_ ? &(*prefixs_) : nullptr;
}

void PigeonListResult::set_prefixs(const EncodableList* value_arg) {
  prefixs_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonListResult::set_prefixs(const EncodableList& value_arg) {
  prefixs_ = value_arg;
}


const std::string* PigeonListResult::page_token() const {
  return page_token_ ? &(*page_token_) : nullptr;
}

void PigeonListResult::set_page_token(const std::string_view* value_arg) {
  page_token_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonListResult::set_page_token(std::string_view value_arg) {
  page_token_ = value_arg;
}


EncodableList PigeonListResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(items_ ? EncodableValue(*items_) : EncodableValue());
  list.push_back(prefixs_ ? EncodableValue(*prefixs_) : EncodableValue());
  list.push_back(page_token_ ? EncodableValue(*page_token_) : EncodableValue());
  return list;
}

PigeonListResult PigeonListResult::FromEncodableList(const EncodableList& list) {
  PigeonListResult decoded;
  auto& encodable_items = list[0];
  if (!encodable_items.IsNull()) {
    decoded.set_items(std::get<EncodableList>(encodable_items));
  }
  auto& encodable_prefixs = list[1];
  if (!encodable_prefixs.IsNull()) {
    decoded.set_prefixs(std::get<EncodableList>(encodable_prefixs));
  }
  auto& encodable_page_token = list[2];
  if (!encodable_page_token.IsNull()) {
    decoded.set_page_token(std::get<std::string>(encodable_page_token));
  }
  return decoded;
}

// PigeonTaskSnapshot

PigeonTaskSnapshot::PigeonTaskSnapshot() {}

PigeonTaskSnapshot::PigeonTaskSnapshot(
  const std::string* handle,
  const int64_t* bytes_transferred,
  const int64_t* total_bytes,
  const int64_t* state,
  const PigeonFullMetaData* metadata)
 : handle_(handle ? std::optional<std::string>(*handle) : std::nullopt),
    bytes_transferred_(bytes_transferred ? std::optional<int64_t>(*bytes_transferred) : std::nullopt),
    total_bytes_(total_bytes ? std::optional<int64_t>(*total_bytes) : std::nullopt),
    state_(state ? std::optional<int64_t>(*state) : std::nullopt),
    metadata_(metadata ? std::make_unique<PigeonFullMetaData>(*metadata) : nullptr) {}

PigeonTaskSnapshot::PigeonTaskSnapshot(const PigeonTaskSnapshot& other)
 : handle_(other.handle_ ? std::optional<std::string>(*other.handle_) : std::nullopt),
    bytes_transferred_(other.bytes_transferred_ ? std::optional<int64_t>(*other.bytes_transferred_) : std::nullopt),
    total_bytes_(other.total_bytes_ ? std::optional<int64_t>(*other.total_bytes_) : std::nullopt),
    state_(other.state_ ? std::optional<int64_t>(*other.state_) : std::nullopt),
    metadata_(other.metadata_ ? std::make_unique<PigeonFullMetaData>(*other.metadata_) : nullptr) {}

PigeonTaskSnapshot& PigeonTaskSnapshot::operator=(const PigeonTaskSnapshot& other) {
  handle_ = other.handle_;
  bytes_transferred_ = other.bytes_transferred_;
  total_bytes_ = other.total_bytes_;
  state_ = other.state_;
  metadata_ = other.metadata_ ? std::make_unique<PigeonFullMetaData>(*other.metadata_) : nullptr;
  return *this;
}

const std::string* PigeonTaskSnapshot::handle() const {
  return handle_ ? &(*handle_) : nullptr;
}

void PigeonTaskSnapshot::set_handle(const std::string_view* value_arg) {
  handle_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PigeonTaskSnapshot::set_handle(std::string_view value_arg) {
  handle_ = value_arg;
}


const int64_t* PigeonTaskSnapshot::bytes_transferred() const {
  return bytes_transferred_ ? &(*bytes_transferred_) : nullptr;
}

void PigeonTaskSnapshot::set_bytes_transferred(const int64_t* value_arg) {
  bytes_transferred_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PigeonTaskSnapshot::set_bytes_transferred(int64_t value_arg) {
  bytes_transferred_ = value_arg;
}


const int64_t* PigeonTaskSnapshot::total_bytes() const {
  return total_bytes_ ? &(*total_bytes_) : nullptr;
}

void PigeonTaskSnapshot::set_total_bytes(const int64_t* value_arg) {
  total_bytes_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PigeonTaskSnapshot::set_total_bytes(int64_t value_arg) {
  total_bytes_ = value_arg;
}


const int64_t* PigeonTaskSnapshot::state() const {
  return state_ ? &(*state_) : nullptr;
}

void PigeonTaskSnapshot::set_state(const int64_t* value_arg) {
  state_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PigeonTaskSnapshot::set_state(int64_t value_arg) {
  state_ = value_arg;
}


const PigeonFullMetaData* PigeonTaskSnapshot::metadata() const {
  return metadata_.get();
}

void PigeonTaskSnapshot::set_metadata(const PigeonFullMetaData* value_arg) {
  metadata_ = value_arg ? std::make_unique<PigeonFullMetaData>(*value_arg) : nullptr;
}

void PigeonTaskSnapshot::set_metadata(const PigeonFullMetaData& value_arg) {
  metadata_ = std::make_unique<PigeonFullMetaData>(value_arg);
}


EncodableList PigeonTaskSnapshot::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(handle_ ? EncodableValue(*handle_) : EncodableValue());
  list.push_back(bytes_transferred_ ? EncodableValue(*bytes_transferred_) : EncodableValue());
  list.push_back(total_bytes_ ? EncodableValue(*total_bytes_) : EncodableValue());
  list.push_back(state_ ? EncodableValue(*state_) : EncodableValue());
  list.push_back(metadata_ ? EncodableValue(metadata_->ToEncodableList()) : EncodableValue());
  return list;
}

PigeonTaskSnapshot PigeonTaskSnapshot::FromEncodableList(const EncodableList& list) {
  PigeonTaskSnapshot decoded;
  auto& encodable_handle = list[0];
  if (!encodable_handle.IsNull()) {
    decoded.set_handle(std::get<std::string>(encodable_handle));
  }
  auto& encodable_bytes_transferred = list[1];
  if (!encodable_bytes_transferred.IsNull()) {
    decoded.set_bytes_transferred(encodable_bytes_transferred.LongValue());
  }
  auto& encodable_total_bytes = list[2];
  if (!encodable_total_bytes.IsNull()) {
    decoded.set_total_bytes(encodable_total_bytes.LongValue());
  }
  auto& encodable_state = list[3];
  if (!encodable_state.IsNull()) {
    decoded.set_state(encodable_state.LongValue());
  }
  auto& encodable_metadata = list[4];
  if (!encodable_metadata.IsNull()) {
    decoded.set_metadata(PigeonFullMetaData::FromEncodableList(std::get<EncodableList>(encodable_metadata)));
  }
  return decoded;
}


FirebaseStorageHostApiCodecSerializer::FirebaseStorageHostApiCodecSerializer() {}

EncodableValue FirebaseStorageHostApiCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 128:
      return CustomEncodableValue(PigeonFullMetaData::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 129:
      return CustomEncodableValue(PigeonListOptions::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 130:
      return CustomEncodableValue(PigeonListResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 131:
      return CustomEncodableValue(PigeonSettableMetaData::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 132:
      return CustomEncodableValue(PigeonSettableMetaData::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
  }
}

void FirebaseStorageHostApiCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(PigeonFullMetaData)) {
      stream->WriteByte(128);
      WriteValue(EncodableValue(std::any_cast<PigeonFullMetaData>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonListOptions)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<PigeonListOptions>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonListResult)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<PigeonListResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonSettableMetaData)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<PigeonSettableMetaData>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonSettableMetaData)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<PigeonSettableMetaData>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FirebaseStorageHostApi.
const flutter::StandardMessageCodec& FirebaseStorageHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&FirebaseStorageHostApiCodecSerializer::GetInstance());
}

// Sets up an instance of `FirebaseStorageHostApi` to handle messages through the `binary_messenger`.
void FirebaseStorageHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FirebaseStorageHostApi* api) {
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.setMaxOperationRetryTime", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_time_arg = args.at(2);
          if (encodable_time_arg.IsNull()) {
            reply(WrapError("time_arg unexpectedly null."));
            return;
          }
          const int64_t time_arg = encodable_time_arg.LongValue();
          api->SetMaxOperationRetryTime(app_name_arg, bucket_arg, time_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.setMaxUploadRetryTime", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_time_arg = args.at(2);
          if (encodable_time_arg.IsNull()) {
            reply(WrapError("time_arg unexpectedly null."));
            return;
          }
          const int64_t time_arg = encodable_time_arg.LongValue();
          api->SetMaxUploadRetryTime(app_name_arg, bucket_arg, time_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.setMaxDownloadRetryTime", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_time_arg = args.at(2);
          if (encodable_time_arg.IsNull()) {
            reply(WrapError("time_arg unexpectedly null."));
            return;
          }
          const int64_t time_arg = encodable_time_arg.LongValue();
          api->SetMaxDownloadRetryTime(app_name_arg, bucket_arg, time_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.useStorageEmulator", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_host_arg = args.at(2);
          if (encodable_host_arg.IsNull()) {
            reply(WrapError("host_arg unexpectedly null."));
            return;
          }
          const auto& host_arg = std::get<std::string>(encodable_host_arg);
          const auto& encodable_port_arg = args.at(3);
          if (encodable_port_arg.IsNull()) {
            reply(WrapError("port_arg unexpectedly null."));
            return;
          }
          const int64_t port_arg = encodable_port_arg.LongValue();
          api->UseStorageEmulator(app_name_arg, bucket_arg, host_arg, port_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceGetDownloadURL", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->ReferenceGetDownloadURL(app_name_arg, bucket_arg, path_arg, [reply](ErrorOr<std::string>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceGetMetaData", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->ReferenceGetMetaData(app_name_arg, bucket_arg, path_arg, [reply](ErrorOr<PigeonFullMetaData>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceUpdateMetaData", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_metadata_arg = args.at(3);
          if (encodable_metadata_arg.IsNull()) {
            reply(WrapError("metadata_arg unexpectedly null."));
            return;
          }
          const auto& metadata_arg = std::any_cast<const PigeonSettableMetaData&>(std::get<CustomEncodableValue>(encodable_metadata_arg));
          api->ReferenceUpdateMetaData(app_name_arg, bucket_arg, path_arg, metadata_arg, [reply](ErrorOr<PigeonFullMetaData>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceDelete", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->ReferenceDelete(app_name_arg, bucket_arg, path_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceGetData", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_max_size_arg = args.at(3);
          if (encodable_max_size_arg.IsNull()) {
            reply(WrapError("max_size_arg unexpectedly null."));
            return;
          }
          const int64_t max_size_arg = encodable_max_size_arg.LongValue();
          api->ReferenceGetData(app_name_arg, bucket_arg, path_arg, max_size_arg, [reply](ErrorOr<std::vector<uint8_t>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceList", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_options_arg = args.at(3);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::any_cast<const PigeonListOptions&>(std::get<CustomEncodableValue>(encodable_options_arg));
          api->ReferenceList(app_name_arg, bucket_arg, path_arg, options_arg, [reply](ErrorOr<PigeonListResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceListAll", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->ReferenceListAll(app_name_arg, bucket_arg, path_arg, [reply](ErrorOr<PigeonListResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskStartPutData", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_metadata_arg = args.at(3);
          const PigeonSettableMetaData* metadata_arg = nullptr;
          if (!encodable_metadata_arg.IsNull()) {
            metadata_arg = &(std::any_cast<const PigeonSettableMetaData&>(std::get<CustomEncodableValue>(encodable_metadata_arg)));
          }
          const auto& encodable_data_arg = args.at(4);
          if (encodable_data_arg.IsNull()) {
            reply(WrapError("data_arg unexpectedly null."));
            return;
          }
          const auto& data_arg = std::get<std::vector<uint8_t>>(encodable_data_arg);
          const auto& encodable_handle_arg = args.at(5);
          if (encodable_handle_arg.IsNull()) {
            reply(WrapError("handle_arg unexpectedly null."));
            return;
          }
          const auto& handle_arg = std::get<std::string>(encodable_handle_arg);
          api->TaskStartPutData(app_name_arg, bucket_arg, path_arg, metadata_arg, data_arg, handle_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskStartPutString", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_data_arg = args.at(3);
          if (encodable_data_arg.IsNull()) {
            reply(WrapError("data_arg unexpectedly null."));
            return;
          }
          const auto& data_arg = std::get<std::string>(encodable_data_arg);
          const auto& encodable_format_arg = args.at(4);
          if (encodable_format_arg.IsNull()) {
            reply(WrapError("format_arg unexpectedly null."));
            return;
          }
          const PigeonStringFormat& format_arg = (PigeonStringFormat)encodable_format_arg.LongValue();
          const auto& encodable_metadata_arg = args.at(5);
          const PigeonSettableMetaData* metadata_arg = nullptr;
          if (!encodable_metadata_arg.IsNull()) {
            metadata_arg = &(std::any_cast<const PigeonSettableMetaData&>(std::get<CustomEncodableValue>(encodable_metadata_arg)));
          }
          const auto& encodable_handle_arg = args.at(6);
          if (encodable_handle_arg.IsNull()) {
            reply(WrapError("handle_arg unexpectedly null."));
            return;
          }
          const auto& handle_arg = std::get<std::string>(encodable_handle_arg);
          api->TaskStartPutString(app_name_arg, bucket_arg, path_arg, data_arg, format_arg, metadata_arg, handle_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskStartPutFile", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_file_path_arg = args.at(3);
          if (encodable_file_path_arg.IsNull()) {
            reply(WrapError("file_path_arg unexpectedly null."));
            return;
          }
          const auto& file_path_arg = std::get<std::string>(encodable_file_path_arg);
          const auto& encodable_metadata_arg = args.at(4);
          const PigeonSettableMetaData* metadata_arg = nullptr;
          if (!encodable_metadata_arg.IsNull()) {
            metadata_arg = &(std::any_cast<const PigeonSettableMetaData&>(std::get<CustomEncodableValue>(encodable_metadata_arg)));
          }
          const auto& encodable_handle_arg = args.at(5);
          if (encodable_handle_arg.IsNull()) {
            reply(WrapError("handle_arg unexpectedly null."));
            return;
          }
          const auto& handle_arg = std::get<std::string>(encodable_handle_arg);
          api->TaskStartPutFile(app_name_arg, bucket_arg, path_arg, file_path_arg, metadata_arg, handle_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskStartWriteToFile", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_bucket_arg = args.at(1);
          if (encodable_bucket_arg.IsNull()) {
            reply(WrapError("bucket_arg unexpectedly null."));
            return;
          }
          const auto& bucket_arg = std::get<std::string>(encodable_bucket_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_file_path_arg = args.at(3);
          if (encodable_file_path_arg.IsNull()) {
            reply(WrapError("file_path_arg unexpectedly null."));
            return;
          }
          const auto& file_path_arg = std::get<std::string>(encodable_file_path_arg);
          const auto& encodable_handle_arg = args.at(4);
          if (encodable_handle_arg.IsNull()) {
            reply(WrapError("handle_arg unexpectedly null."));
            return;
          }
          const auto& handle_arg = std::get<std::string>(encodable_handle_arg);
          api->TaskStartWriteToFile(app_name_arg, bucket_arg, path_arg, file_path_arg, handle_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskPause", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_handle_arg = args.at(0);
          if (encodable_handle_arg.IsNull()) {
            reply(WrapError("handle_arg unexpectedly null."));
            return;
          }
          const auto& handle_arg = std::get<std::string>(encodable_handle_arg);
          api->TaskPause(handle_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskResume", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_handle_arg = args.at(0);
          if (encodable_handle_arg.IsNull()) {
            reply(WrapError("handle_arg unexpectedly null."));
            return;
          }
          const auto& handle_arg = std::get<std::string>(encodable_handle_arg);
          api->TaskResume(handle_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskCancel", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_handle_arg = args.at(0);
          if (encodable_handle_arg.IsNull()) {
            reply(WrapError("handle_arg unexpectedly null."));
            return;
          }
          const auto& handle_arg = std::get<std::string>(encodable_handle_arg);
          api->TaskCancel(handle_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FirebaseStorageHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FirebaseStorageHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}


FirebaseStorageFlutterApiCodecSerializer::FirebaseStorageFlutterApiCodecSerializer() {}

EncodableValue FirebaseStorageFlutterApiCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 128:
      return CustomEncodableValue(PigeonFullMetaData::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 129:
      return CustomEncodableValue(PigeonTaskSnapshot::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
  }
}

void FirebaseStorageFlutterApiCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(PigeonFullMetaData)) {
      stream->WriteByte(128);
      WriteValue(EncodableValue(std::any_cast<PigeonFullMetaData>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonTaskSnapshot)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<PigeonTaskSnapshot>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
FirebaseStorageFlutterApi::FirebaseStorageFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger) {}

const flutter::StandardMessageCodec& FirebaseStorageFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&FirebaseStorageFlutterApiCodecSerializer::GetInstance());
}

void FirebaseStorageFlutterApi::OnTaskEvent(
  const std::string& handle_arg,
  const PigeonTaskSnapshot& snapshot_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskEvent";
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(handle_arg),
    CustomEncodableValue(snapshot_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void FirebaseStorageFlutterApi::OnTaskError(
  const std::string& handle_arg,
  int64_t error_code_arg,
  const std::string& message_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskError";
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(handle_arg),
    EncodableValue(error_code_arg),
    EncodableValue(message_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace firebase_storage_webos
