name: webos_lint
version: 1.0.0
description: Custom lint rules for webOS Flutter Apps.

environment:
  sdk: ^3.1.5

dependencies:
  analyzer: '>=7.3.0 <8.0.0'
  analyzer_plugin:
  custom_lint_builder: ^0.8.0
