name: connectivity_plus_example
description: Demonstrates how to use the connectivity_plus_webos plugin.
publish_to: "none"

dependencies:
  connectivity_plus: ^6.1.0
  connectivity_plus_webos:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^5.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"
