// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum PigeonStringFormat {
  raw,
  base64,
  base64Url,
  dataUrl,
}

/// Settable metadata fields for an upload.
class PigeonSettableMetaData {
  PigeonSettableMetaData({
    this.cacheControl,
    this.contentDisposition,
    this.contentEncoding,
    this.contentLanguage,
    this.contentType,
    this.customMetadata,
  });

  String? cacheControl;

  String? contentDisposition;

  String? contentEncoding;

  String? contentLanguage;

  String? contentType;

  Map<String?, String?>? customMetadata;

  Object encode() {
    return <Object?>[
      cacheControl,
      contentDisposition,
      contentEncoding,
      contentLanguage,
      contentType,
      customMetadata,
    ];
  }

  static PigeonSettableMetaData decode(Object result) {
    result as List<Object?>;
    return PigeonSettableMetaData(
      cacheControl: result[0] as String?,
      contentDisposition: result[1] as String?,
      contentEncoding: result[2] as String?,
      contentLanguage: result[3] as String?,
      contentType: result[4] as String?,
      customMetadata: (result[5] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }
}

/// Full metadata returned by the server.
class PigeonFullMetaData {
  PigeonFullMetaData({
    this.metadata,
  });

  Map<String?, Object?>? metadata;

  Object encode() {
    return <Object?>[
      metadata,
    ];
  }

  static PigeonFullMetaData decode(Object result) {
    result as List<Object?>;
    return PigeonFullMetaData(
      metadata: (result[0] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }
}

/// Options for listing items under a storage reference.
class PigeonListOptions {
  PigeonListOptions({
    this.maxResults,
    this.pageToken,
  });

  int? maxResults;

  String? pageToken;

  Object encode() {
    return <Object?>[
      maxResults,
      pageToken,
    ];
  }

  static PigeonListOptions decode(Object result) {
    result as List<Object?>;
    return PigeonListOptions(
      maxResults: result[0] as int?,
      pageToken: result[1] as String?,
    );
  }
}

/// Result of a list/listAll operation.
class PigeonListResult {
  PigeonListResult({
    this.items,
    this.prefixs,
    this.pageToken,
  });

  List<String?>? items;

  List<String?>? prefixs;

  String? pageToken;

  Object encode() {
    return <Object?>[
      items,
      prefixs,
      pageToken,
    ];
  }

  static PigeonListResult decode(Object result) {
    result as List<Object?>;
    return PigeonListResult(
      items: (result[0] as List<Object?>?)?.cast<String?>(),
      prefixs: (result[1] as List<Object?>?)?.cast<String?>(),
      pageToken: result[2] as String?,
    );
  }
}

/// A snapshot of an ongoing transfer task.
class PigeonTaskSnapshot {
  PigeonTaskSnapshot({
    this.handle,
    this.bytesTransferred,
    this.totalBytes,
    this.state,
    this.metadata,
  });

  String? handle;

  int? bytesTransferred;

  int? totalBytes;

  /// 0 = paused, 1 = running, 2 = success, 3 = canceled, 4 = error
  int? state;

  PigeonFullMetaData? metadata;

  Object encode() {
    return <Object?>[
      handle,
      bytesTransferred,
      totalBytes,
      state,
      metadata?.encode(),
    ];
  }

  static PigeonTaskSnapshot decode(Object result) {
    result as List<Object?>;
    return PigeonTaskSnapshot(
      handle: result[0] as String?,
      bytesTransferred: result[1] as int?,
      totalBytes: result[2] as int?,
      state: result[3] as int?,
      metadata: result[4] != null
          ? PigeonFullMetaData.decode(result[4]! as List<Object?>)
          : null,
    );
  }
}

class _FirebaseStorageHostApiCodec extends StandardMessageCodec {
  const _FirebaseStorageHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonFullMetaData) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PigeonListOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PigeonListResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PigeonSettableMetaData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PigeonSettableMetaData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonFullMetaData.decode(readValue(buffer)!);
      case 129: 
        return PigeonListOptions.decode(readValue(buffer)!);
      case 130: 
        return PigeonListResult.decode(readValue(buffer)!);
      case 131: 
        return PigeonSettableMetaData.decode(readValue(buffer)!);
      case 132: 
        return PigeonSettableMetaData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FirebaseStorageHostApi {
  /// Constructor for [FirebaseStorageHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FirebaseStorageHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _FirebaseStorageHostApiCodec();

  Future<void> setMaxOperationRetryTime(String appName, String bucket, int time) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.setMaxOperationRetryTime';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, time]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setMaxUploadRetryTime(String appName, String bucket, int time) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.setMaxUploadRetryTime';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, time]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setMaxDownloadRetryTime(String appName, String bucket, int time) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.setMaxDownloadRetryTime';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, time]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> useStorageEmulator(String appName, String bucket, String host, int port) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.useStorageEmulator';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, host, port]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> referenceGetDownloadURL(String appName, String bucket, String path) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceGetDownloadURL';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as String?)!;
    }
  }

  Future<PigeonFullMetaData> referenceGetMetaData(String appName, String bucket, String path) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceGetMetaData';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonFullMetaData?)!;
    }
  }

  Future<PigeonFullMetaData> referenceUpdateMetaData(String appName, String bucket, String path, PigeonSettableMetaData metadata) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceUpdateMetaData';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path, metadata]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonFullMetaData?)!;
    }
  }

  Future<void> referenceDelete(String appName, String bucket, String path) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceDelete';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<Uint8List> referenceGetData(String appName, String bucket, String path, int maxSize) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceGetData';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path, maxSize]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as Uint8List?)!;
    }
  }

  Future<PigeonListResult> referenceList(String appName, String bucket, String path, PigeonListOptions options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceList';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path, options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonListResult?)!;
    }
  }

  Future<PigeonListResult> referenceListAll(String appName, String bucket, String path) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.referenceListAll';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonListResult?)!;
    }
  }

  Future<void> taskStartPutData(String appName, String bucket, String path, PigeonSettableMetaData? metadata, Uint8List data, String handle) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskStartPutData';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path, metadata, data, handle]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> taskStartPutString(String appName, String bucket, String path, String data, PigeonStringFormat format, PigeonSettableMetaData? metadata, String handle) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskStartPutString';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path, data, format.index, metadata, handle]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> taskStartPutFile(String appName, String bucket, String path, String filePath, PigeonSettableMetaData? metadata, String handle) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskStartPutFile';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path, filePath, metadata, handle]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> taskStartWriteToFile(String appName, String bucket, String path, String filePath, String handle) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskStartWriteToFile';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, bucket, path, filePath, handle]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> taskPause(String handle) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskPause';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[handle]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> taskResume(String handle) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskResume';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[handle]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> taskCancel(String handle) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageHostApi.taskCancel';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[handle]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

class _FirebaseStorageFlutterApiCodec extends StandardMessageCodec {
  const _FirebaseStorageFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonFullMetaData) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PigeonTaskSnapshot) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonFullMetaData.decode(readValue(buffer)!);
      case 129: 
        return PigeonTaskSnapshot.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FirebaseStorageFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _FirebaseStorageFlutterApiCodec();

  void onTaskEvent(String handle, PigeonTaskSnapshot snapshot);

  void onTaskError(String handle, int errorCode, String message);

  static void setup(FirebaseStorageFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskEvent', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskEvent was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_handle = (args[0] as String?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskEvent was null, expected non-null String.');
          final PigeonTaskSnapshot? arg_snapshot = (args[1] as PigeonTaskSnapshot?);
          assert(arg_snapshot != null,
              'Argument for dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskEvent was null, expected non-null PigeonTaskSnapshot.');
          try {
            api.onTaskEvent(arg_handle!, arg_snapshot!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskError', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_handle = (args[0] as String?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskError was null, expected non-null String.');
          final int? arg_errorCode = (args[1] as int?);
          assert(arg_errorCode != null,
              'Argument for dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskError was null, expected non-null int.');
          final String? arg_message = (args[2] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.firebase_storage_webos.FirebaseStorageFlutterApi.onTaskError was null, expected non-null String.');
          try {
            api.onTaskError(arg_handle!, arg_errorCode!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
